- apps/gdmn-nxt-server/src/main.ts
- apps/gdmn-nxt-web/src/app/app.tsx
Fixed 400 and 401 errors, added sign in
> Signin fix

- apps/gdmn-nxt-server/src/app/reconciliationStatement.ts
- apps/gdmn-nxt-server/src/main.ts
- apps/gdmn-nxt-web/src/app/customer-home-page/customer-home-page.tsx
- apps/gdmn-nxt-web/src/app/features/reconciliation-statement/reconciliationStatementApi.ts
- apps/gdmn-nxt-web/src/app/reconciliation-statement/reconciliation-statement.tsx
- apps/gdmn-nxt-web/src/app/store.ts
- apps/gdmn-nxt-web/src/main.tsx
- libs/util-api-types/src/index.ts
- libs/util-api-types/src/lib/commonDataTypes.ts
- libs/util-api-types/src/lib/crmDataTypes.ts
- libs/util-useful/src/lib/util-useful.ts
Use RTK Query for the reconciliation statement fetching from the server.
> Reconciliation

- apps/gdmn-nxt-web/src/app/confirm-dialog/confirm-dialog.spec.tsx
- apps/gdmn-nxt-web/src/app/confirm-dialog/confirm-dialog.tsx
- apps/gdmn-nxt-web/src/app/customer-edit/customer-edit.spec.tsx
- apps/gdmn-nxt-web/src/app/customer-edit/customer-edit.tsx
- apps/gdmn-nxt-web/src/app/customers/customers.tsx
- yarn.lock
Пока без обновления базы данных, без стилей красивых.
Хочу сначала разобраться в Redux toolkit.
> Customer edit

- apps/gdmn-nxt-web/src/app/pages/FAQ/Index.tsx
- apps/gdmn-nxt-web/src/app/pages/FAQ/faq.module.less
Убрал кнопки crud, т.к. пока в них нет необходимости в вебе. Только портят вёртску
> fix: styles in .less and fix error

- apps/gdmn-nxt-web/src/app/components/Labels/label-list-item-edit/label-list-item-edit.tsx
> 60 symbol max length

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/task.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-task/kanban-edit-task.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/gsbelarus/gdmn-nxt/issues/247
> feat: button in progress

- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-collapse/menu-collapse.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-item/menu-item.tsx
- apps/gdmn-nxt-web/src/app/menu-items/managment.tsx
> fix: opening list of menu items when one of the list item is active

- apps/gdmn-nxt-server/src/app/controllers/kanban/cards.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/272
> fix: duplicate records of request table

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/custom-grid-tree-data-grouping-cell.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/kanban-list.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-list/kanban-tasks-list.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/hooks/useDateComparator.tsx
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-deals/customer-deals.module.less
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-deals/customer-deals.spec.tsx
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-deals/customer-deals.tsx
- apps/gdmn-nxt-web/src/app/pages/Customers/customer-details/customer-details.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/deals/deals.module.less
- apps/gdmn-nxt-web/src/app/pages/Managment/deals/deals.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/tasks/tasks.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/gsbelarus/gdmn-nxt/issues/271
> feat: новая вкладка Сделки

- apps/gdmn-nxt-server/src/app/controllers/kanban/cards.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/history.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/task.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-board/kanban-board.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-task/kanban-edit-task.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/kanban-list.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks/kanban-tasks.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/deals/deals.tsx
- libs/util-api-types/src/lib/commonDataTypes.ts
- libs/util-helpers/src/lib/named-params.ts
https://github.com/gsbelarus/gdmn-nxt/issues/267
> chore: формирование истории изменений на бэке

- apps/gdmn-nxt-web/src/app/components/Styled/customized-card/customized-card.tsx
- apps/gdmn-nxt-web/src/app/components/Styled/customized-scroll-box/customized-scroll-box.module.less
- apps/gdmn-nxt-web/src/app/components/Styled/customized-scroll-box/customized-scroll-box.tsx
- apps/gdmn-nxt-web/src/app/components/updates/updates-edit/updates-edit.module.less
- apps/gdmn-nxt-web/src/app/components/updates/updates-edit/updates-edit.tsx
- apps/gdmn-nxt-web/src/app/components/updates/updates-list/updates-list.module.less
- apps/gdmn-nxt-web/src/app/components/updates/updates-list/updates-list.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/285
> chore: new universal scrollbox

- apps/gdmn-nxt-web/src/app/components/updates/updates-edit/updates-edit.module.less
- apps/gdmn-nxt-web/src/app/components/updates/updates-edit/updates-edit.tsx
[#288](https://github.com/gsbelarus/gdmn-nxt/issues/288)
> input at full height

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/tasks-filter/tasks-filter.spec.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/tasks-filter/tasks-filter.tsx
- apps/gdmn-nxt-web/src/app/features/kanban/kanbanApi.ts
- apps/gdmn-nxt-web/src/app/pages/Managment/tasks/tasks.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/305
> chore: добавлен фильтр задач по исполнителям

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/components/customer-select.tsx
- apps/gdmn-nxt-web/src/app/features/customer/customerApi_new.ts
https://github.com/gsbelarus/gdmn-nxt/issues/298
> fix: создание клиента при создании сделки

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/components/tab-descrption.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-list/kanban-tasks-list.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/sidebar-view/sidebar-view.tsx
- адаптивное боковое меню для разных размеров экранов
- поле Описание для сделки на весь экран
> style: немного красоты

- apps/gdmn-nxt-web/src/app/components/Styled/customized-scroll-box/customized-scroll-box.tsx
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/notification-center/notification-center.module.less
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/notification-center/notification-center.tsx
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/notifications-settings/notifications-settings.module.less
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/notifications-settings/notifications-settings.tsx
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/send-message/send-message.module.less
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/send-message/send-message.tsx
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/view-user-notifications/view-user-notifications.module.less
- apps/gdmn-nxt-web/src/app/pages/NotificationCenter/view-user-notifications/view-user-notifications.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/315
> style: notifications center

- apps/gdmn-nxt-web/src/index.html
- apps/gdmn-nxt-web/src/main.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/323
> fix: set original language as russian

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/deals-filter/deals-filter.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/321
> feat: added filter by performers

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
> feat: add year to deadline

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-board/kanban-board.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-column/kanban-column.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/components/customer-select.tsx
#334
and fix old data after deal create
> fix: creating client from creating deal

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-list/kanban-tasks-list.tsx
> feat: short name, creator field, sorting

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/task-status.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/hooks/useDateComparator.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/hooks/useDeadlineColor.tsx
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-deals/customer-deals.tsx
> feat: tooltip for kanban cards

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
> fix: deal copy

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/task.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
- apps/gdmn-nxt-web/src/app/features/kanban/kanbanApi.ts
https://github.com/gsbelarus/gdmn-nxt/issues/332
> chore: непрочитанные задачи

- apps/gdmn-nxt-web/src/app/components/Charts/chart-donut/chart-donut.tsx
> feat: procent for donut labels

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
> chore: styles for tasks cards

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/task.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-task/kanban-edit-task.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/gsbelarus/gdmn-nxt/issues/351
> chore: comments for done deals

- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/sidebar-view/sidebar-view.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/index.tsx
> fix: add menuBar open button

- apps/gdmn-nxt-server/src/app/controllers/kanban/cards.ts
- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-server/src/app/routes/socket/notifications/index.ts
- apps/gdmn-nxt-server/src/app/utils/db-connection.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/gsbelarus/gdmn-nxt/issues/354
> chore: новые этапы сделок

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
> fix: max width taks description and theme update for kanban card

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-column/kanban-column.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/2654
> feat: tables permissions

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
https://github.com/gsbelarus/gdmn-nxt/issues/386
> chore: view permissions

- apps/gdmn-nxt-server/src/app/controllers/kanban/cards.ts
https://github.com/gsbelarus/gdmn-nxt/issues/381
> chore: added events to chronology tab

- apps/gdmn-nxt-web/src/app/components/updates/updates-info/updates-info.module.less
- apps/gdmn-nxt-web/src/app/components/updates/updates-info/updates-info.tsx
> fix: dynamic popup height

- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Header/toggle-theme/toggle-theme.tsx
- apps/gdmn-nxt-web/src/app/pages/Preferences/account-settings/account-settings.tsx
- apps/gdmn-nxt-web/src/app/pages/Preferences/profile/profile.tsx
> fix: clear file input and copy settings for setSettings

- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-group/menu-group.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/menu-list/menu-list.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Sidebar/sidebar-view/sidebar-view.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/432
> feat: added search

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/deals-filter/deals-filter.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/tasks-filter/tasks-filter.tsx
- apps/gdmn-nxt-web/src/app/features/kanban/kanbanApi.ts
https://github.com/gsbelarus/gdmn-nxt/issues/428
> feat: added new filters

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-column/kanban-column.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-card/kanban-edit-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-task/kanban-edit-task.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/kanban-list.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks/kanban-tasks.tsx
- apps/gdmn-nxt-web/src/app/components/Labels/label-list-item-edit/label-list-item-edit.tsx
- apps/gdmn-nxt-web/src/app/components/Permissions/user-group-edit/user-group-edit.tsx
- apps/gdmn-nxt-web/src/app/components/Permissions/user-group-line-edit/user-group-line-edit.tsx
- apps/gdmn-nxt-web/src/app/customers/customer-edit/customer-edit.tsx
- apps/gdmn-nxt-web/src/app/customers/customers-filter/customers-filter.tsx
- apps/gdmn-nxt-web/src/app/customers/person-edit/person-edit.tsx
- apps/gdmn-nxt-web/src/app/pages/Analytics/UserReports/ReconciliationAct.tsx
- apps/gdmn-nxt-web/src/app/theme/componentStyleOverrides.ts
- libs/ui-common-dialogs/src/lib/sign-in-sign-up/sign-in-sign-up.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/447
> feat: tasks

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks/kanban-tasks.tsx
- apps/gdmn-nxt-web/src/app/components/search-bar/search-bar.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/deals/deals.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/tasks/tasks.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/458
> feat: searchbar for deals and tasks

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/pages/Managment/deals/deals.tsx
- apps/gdmn-nxt-web/src/app/pages/Managment/tasks/tasks.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/458
> chore: extended search

- apps/gdmn-nxt-web/src/app/components/Charts/chart-donut/chart-donut.tsx
- apps/gdmn-nxt-web/src/app/theme/componentStyleOverrides.ts
> style: scroll color

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-edit-task/kanban-edit-task.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-list/kanban-tasks-list.tsx
- apps/gdmn-nxt-web/src/app/components/Styled/customized-dialog/customized-dialog.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/461
> fix: infinite re-render

- apps/gdmn-nxt-web/src/app/components/search-bar/search-bar.tsx
> trasition for closing search bar

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
> styles: popup closing animation

- apps/gdmn-nxt-web/src/app/components/Contacts/contact-cards/contact-cards.module.less
- apps/gdmn-nxt-web/src/app/components/Contacts/contact-cards/contact-cards.tsx
- apps/gdmn-nxt-web/src/app/components/social-media-input/index.tsx
- apps/gdmn-nxt-web/src/app/components/social-media-input/social-media-links/index.ts
https://github.com/gsbelarus/gdmn-nxt/issues/487
> chore: messengers links

- apps/gdmn-nxt-web/src/app/components/Labels/label-marker/label-marker.tsx
- apps/gdmn-nxt-web/src/app/components/editable-avatar/editable-avatar.module.less
- apps/gdmn-nxt-web/src/app/components/editable-avatar/editable-avatar.tsx
- apps/gdmn-nxt-web/src/app/pages/Preferences/profile/profile.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/472
> style: labels and avatar

- apps/gdmn-nxt-server/src/app/controllers/app.ts
- apps/gdmn-nxt-server/src/app/controllers/permissions.ts
- apps/gdmn-nxt-server/src/app/controllers/profileSettings.ts
- apps/gdmn-nxt-server/src/app/middlewares/permissions.ts
- apps/gdmn-nxt-server/src/app/repositories/contacts/contactPersons.ts
- apps/gdmn-nxt-server/src/app/routes/profileSettings.ts
- apps/gdmn-nxt-server/src/app/utils/sessions-helper.ts
- apps/gdmn-nxt-web/src/app/app.tsx
- apps/gdmn-nxt-web/src/app/components/Contacts/edit-contact/edit-contact.tsx
- apps/gdmn-nxt-web/src/app/components/Labels/label-list-item/label-list-item.tsx
- apps/gdmn-nxt-web/src/app/components/Permissions/user-group-edit/user-group-edit.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/confirmation/index.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/menu-burger/index.tsx
- apps/gdmn-nxt-web/src/app/components/item-button-delete/item-button-delete.tsx
- apps/gdmn-nxt-web/src/app/confirm-dialog/confirm-dialog.tsx
- apps/gdmn-nxt-web/src/app/features/profileSettings/index.ts
- apps/gdmn-nxt-web/src/app/pages/Permissions/user-groups/user-groups-line.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/471
> feat: reset user settings

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
> fix: card height fix on card focus

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/task-status.tsx
> chore: console error

- apps/gdmn-nxt-server/src/app/controllers/kanban/kanban.ts
- apps/gdmn-nxt-web/src/app/components/Contacts/contact-cards/contact-cards.tsx
- apps/gdmn-nxt-web/src/app/components/Contacts/contacts-deals/index.tsx
- apps/gdmn-nxt-web/src/app/components/Contacts/contacts-filter/contacts-filter.tsx
- apps/gdmn-nxt-web/src/app/components/Contacts/edit-contact/edit-contact.module.less
- apps/gdmn-nxt-web/src/app/components/Contacts/edit-contact/edit-contact.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/kanban-list.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-card/kanban-tasks-card.tsx
- apps/gdmn-nxt-web/src/app/components/Styled/styled-grid/styled-grid.tsx
- apps/gdmn-nxt-web/src/app/components/helpers/hooks/useUserData.tsx
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-contacts/index.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/472
> feat: added deals list to contacts

- apps/gdmn-nxt-web/src/app/components/Contacts/contact-tasks/index.tsx
- apps/gdmn-nxt-web/src/app/components/Contacts/edit-contact/edit-contact.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-tasks-list/kanban-tasks-list.spec.tsx
https://github.com/gsbelarus/gdmn-nxt/issues/472
> feat: added task tab

- apps/gdmn-nxt-server/src/app/controllers/permissions.ts
- apps/gdmn-nxt-web/src/app/pages/Permissions/user-groups/user-groups-line.tsx
- libs/util-api-types/src/lib/crmDataTypes.ts
https://github.com/gsbelarus/gdmn-nxt/issues/505
> chore: activated user marker

- apps/gdmn-nxt-web/src/app/components/editable-avatar/editable-avatar.module.less
- apps/gdmn-nxt-web/src/app/components/editable-avatar/editable-avatar.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Header/NotificationSection/notification/notification.tsx
- apps/gdmn-nxt-web/src/app/layouts/MainLayout/Header/profile/profile.tsx
> fix: arrow

- apps/gdmn-nxt-web/src/app/components/Contacts/contact-list/contact-list.tsx
- apps/gdmn-nxt-web/src/app/components/Styled/styled-grid/styled-grid.tsx
> fix: the height of the list row

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/kanban-card.tsx
- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-card/task-status.tsx
> fix: open deal edit on edit task popup

- apps/gdmn-nxt-web/src/app/components/search-bar/search-bar.tsx
> fix: search bar width

- apps/gdmn-nxt-web/src/app/components/Kanban/kanban-list/kanban-list.tsx
- apps/gdmn-nxt-web/src/app/customers/CustomerDetails/customer-deals/customer-deals.tsx
> feat: edit deal from customer list

- apps/gdmn-nxt-web/src/app/pages/Managment/contracts/columns.tsx
> feat: arrow for documents

- libs/ui-common-dialogs/src/lib/verify-code/verify-code.tsx
> feat:auto send 2FA
